/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/users/me": {
    get: operations["getCurrentUser"];
    put: operations["updateProfile"];
  };
  "/api/tasks/{taskId}/comments/{commentId}": {
    put: operations["updateComment"];
    delete: operations["deleteComment"];
  };
  "/api/projects/{projectKey}": {
    get: operations["getProject"];
    put: operations["updateProject"];
    delete: operations["deleteProject"];
  };
  "/api/projects/{projectKey}/tasks/{taskKey}": {
    put: operations["updateTask"];
    delete: operations["deleteTask"];
  };
  "/api/users": {
    post: operations["register"];
  };
  "/api/tasks/{taskId}/comments": {
    get: operations["getComments"];
    post: operations["addComment"];
  };
  "/api/tasks/{taskId}/comments/{commentId}/reactions": {
    post: operations["reactToComment"];
  };
  "/api/projects": {
    get: operations["getProjects"];
    post: operations["createProject"];
  };
  "/api/projects/{projectKey}/tasks": {
    post: operations["createTask"];
  };
  "/api/optimization/simulate": {
    post: operations["simulate"];
  };
  "/api/optimization/apply": {
    post: operations["apply"];
  };
  "/api/notifications/mark-as-read": {
    post: operations["markAsRead"];
  };
  "/api/notifications/mark-all-read": {
    post: operations["markAllRead"];
  };
  "/api/auth/refresh": {
    post: operations["refresh"];
  };
  "/api/auth/logout": {
    post: operations["logout"];
  };
  "/api/auth/login": {
    post: operations["login"];
  };
  "/api/users/me/email-preferences": {
    patch: operations["updateEmailPreferences"];
  };
  "/api/projects/{projectKey}/tasks/{taskKey}/schedule": {
    patch: operations["updateSchedule"];
  };
  "/files/{fileName}": {
    get: operations["serveFile"];
  };
  "/api/users/lookup": {
    get: operations["lookupByEmail"];
  };
  "/api/tasks/{taskId}/activities": {
    get: operations["getActivities"];
  };
  "/api/search": {
    get: operations["search"];
  };
  "/api/notifications": {
    get: operations["getNotifications"];
  };
  "/api/notifications/unread-count": {
    get: operations["getUnreadCount"];
  };
  "/api/notifications/stream": {
    get: operations["streamNotifications"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    CurrentUserDTO: {
      /** Format: int32 */
      id?: number;
      firstname?: string;
      lastname?: string;
      email?: string;
      profilePicture?: string;
      emailNotificationsEnabled?: boolean;
      emailOnTaskAssigned?: boolean;
      emailOnCommentReply?: boolean;
      emailOnProjectInvitation?: boolean;
    };
    CommentDTO: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      taskId?: number;
      /** Format: int32 */
      authorId?: number;
      authorName?: string;
      authorProfilePicture?: string;
      content?: string;
      /** Format: date-time */
      timestamp?: string;
      /** Format: date-time */
      editedAt?: string;
      attachments?: string[];
      /** Format: int32 */
      likeCount?: number;
      /** Format: int32 */
      dislikeCount?: number;
      likedByUsernames?: string[];
      dislikedByUsernames?: string[];
      likedByCurrentUser?: boolean;
      dislikedByCurrentUser?: boolean;
      replies?: components["schemas"]["CommentDTO"][];
    };
    ProjectDTO: {
      /** Format: int32 */
      id?: number;
      projectKey?: string;
      summary?: string;
      description?: string;
      tasks?: components["schemas"]["TaskDTO"][];
      members?: components["schemas"]["UserDTO"][];
      attachments?: string[];
      owner?: components["schemas"]["UserDTO"];
      dependencies?: string[];
      /** Format: date-time */
      created?: string;
      /** Format: date-time */
      updated?: string;
    };
    TaskDTO: {
      /** Format: int32 */
      id?: number;
      /** Format: int32 */
      taskNumber?: number;
      taskKey?: string;
      projectKey?: string;
      summary?: string;
      description?: string;
      /** @enum {string} */
      status?: "BACKLOG" | "GATHERING_INTEREST" | "TODO" | "WITHDRAWN" | "IN_PROGRESS" | "TO_REVIEW" | "TO_TEST" | "IN_TEST" | "READY_TO_MERGE" | "READY_TO_DEPLOY" | "RELEASED" | "DONE";
      /** Format: date */
      startDate?: string;
      /** Format: date */
      dueDate?: string;
      assignee?: string;
      labels?: string[];
      dependencyKeys?: string[];
      isCritical?: boolean;
      /** Format: int32 */
      totalFloat?: number;
      attachments?: string[];
      /** Format: date-time */
      created?: string;
      /** Format: date-time */
      updated?: string;
      /** Format: int32 */
      progress?: number;
      /** @enum {string} */
      priority?: "LOWEST" | "LOW" | "MEDIUM" | "HIGH" | "HIGHEST";
    };
    UserDTO: {
      /** Format: int32 */
      id?: number;
      firstname?: string;
      lastname?: string;
      email?: string;
      profilePicture?: string;
    };
    UserRegistrationRequest: {
      firstname?: string;
      lastname?: string;
      email?: string;
      password?: string;
    };
    LoginResponse: {
      message?: string;
      /** Format: int32 */
      userId?: number;
      email?: string;
      name?: string;
    };
    OptimizationRequest: {
      projectKeys?: string[];
      /** Format: double */
      alpha?: number;
      /** Format: double */
      beta?: number;
      /** Format: date */
      horizonStart?: string;
    };
    OptimizationMetricsDTO: {
      /** Format: double */
      weightedTardiness?: number;
      /** Format: int32 */
      makespan?: number;
      /** Format: double */
      objectiveValue?: number;
      /** Format: int32 */
      totalTasks?: number;
      /** Format: int32 */
      tasksOnTime?: number;
      /** Format: int32 */
      tasksLate?: number;
      /** Format: int32 */
      resourceConflicts?: number;
      feasible?: boolean;
    };
    OptimizationResultDTO: {
      suggestions?: components["schemas"]["TaskScheduleSuggestionDTO"][];
      originalMetrics?: components["schemas"]["OptimizationMetricsDTO"];
      optimizedMetrics?: components["schemas"]["OptimizationMetricsDTO"];
      /** Format: int32 */
      tasksShifted?: number;
      chosenRule?: string;
      skippedTaskKeys?: string[];
    };
    TaskScheduleSuggestionDTO: {
      taskKey?: string;
      projectKey?: string;
      summary?: string;
      assignee?: string;
      /** Format: date */
      originalStartDate?: string;
      /** Format: date */
      originalDueDate?: string;
      /** Format: date */
      suggestedStartDate?: string;
      /** Format: date */
      suggestedDueDate?: string;
      /** Format: int32 */
      priorityWeight?: number;
      /** Format: int32 */
      tardinessDays?: number;
      isCritical?: boolean;
      wasShifted?: boolean;
    };
    ApplyOptimizationRequest: {
      projectKeys?: string[];
      /** Format: double */
      alpha?: number;
      /** Format: double */
      beta?: number;
      /** Format: date */
      horizonStart?: string;
      acceptedTaskKeys?: string[];
    };
    AppliedSchedule: {
      /** Format: int32 */
      tasksUpdated?: number;
    };
    UnreadCount: {
      /** Format: int64 */
      count?: number;
    };
    MessageResponse: {
      message?: string;
    };
    LoginRequest: {
      email?: string;
      password?: string;
    };
    EmailPreferencesRequest: {
      emailNotificationsEnabled?: boolean;
      emailOnTaskAssigned?: boolean;
      emailOnCommentReply?: boolean;
      emailOnProjectInvitation?: boolean;
    };
    TaskScheduleRequest: {
      /** Format: date */
      startDate: string;
      /** Format: date */
      dueDate: string;
      dateRangeOrdered?: boolean;
    };
    PagedResponseCommentDTO: {
      content?: components["schemas"]["CommentDTO"][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      hasNext?: boolean;
    };
    PagedResponseTaskActivityDTO: {
      content?: components["schemas"]["TaskActivityDTO"][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      hasNext?: boolean;
    };
    TaskActivityDTO: {
      /** Format: int32 */
      id?: number;
      /** @enum {string} */
      type?: "CREATED" | "STATUS_CHANGED" | "PRIORITY_CHANGED" | "ASSIGNEE_CHANGED" | "PROGRESS_CHANGED" | "DATES_CHANGED" | "SUMMARY_CHANGED" | "DESCRIPTION_CHANGED" | "LABELS_CHANGED" | "DEPENDENCIES_CHANGED" | "ATTACHMENTS_CHANGED" | "COMMENT_ADDED" | "COMMENT_EDITED" | "COMMENT_DELETED";
      fieldName?: string;
      oldValue?: string;
      newValue?: string;
      authorName?: string;
      authorProfilePicture?: string;
      /** Format: date-time */
      timestamp?: string;
    };
    CommentResult: {
      /** Format: int32 */
      commentId?: number;
      /** Format: int32 */
      taskId?: number;
      taskKey?: string;
      authorName?: string;
      snippet?: string;
    };
    ProjectResult: {
      projectKey?: string;
      summary?: string;
      description?: string;
    };
    SearchResultDTO: {
      projects?: components["schemas"]["ProjectResult"][];
      tasks?: components["schemas"]["TaskResult"][];
      comments?: components["schemas"]["CommentResult"][];
    };
    TaskResult: {
      taskKey?: string;
      projectKey?: string;
      summary?: string;
      status?: string;
      priority?: string;
      assigneeName?: string;
    };
    PagedResponseProjectDTO: {
      content?: components["schemas"]["ProjectDTO"][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      hasNext?: boolean;
    };
    NotificationDTO: {
      /** Format: int32 */
      id?: number;
      message?: string;
      /** Format: date-time */
      timestamp?: string;
      isRead?: boolean;
      /** @enum {string} */
      type?: "PROJECT_INVITATION" | "PROJECT_UPDATED" | "MEMBER_REMOVED" | "TASK_ASSIGNED" | "TASK_UPDATED" | "TASK_COMMENT" | "TASK_DELETED" | "COMMENT_REPLY" | "COMMENT_REACTION";
      link?: string;
    };
    PagedResponseNotificationDTO: {
      content?: components["schemas"]["NotificationDTO"][];
      /** Format: int32 */
      page?: number;
      /** Format: int32 */
      size?: number;
      /** Format: int64 */
      totalElements?: number;
      /** Format: int32 */
      totalPages?: number;
      hasNext?: boolean;
    };
    SseEmitter: {
      /** Format: int64 */
      timeout?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  getCurrentUser: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CurrentUserDTO"];
        };
      };
    };
  };
  updateProfile: {
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          profile: string;
          /** Format: binary */
          profilePicture?: string;
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CurrentUserDTO"];
        };
      };
    };
  };
  updateComment: {
    parameters: {
      path: {
        taskId: number;
        commentId: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          content: string;
          attachments?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CommentDTO"];
        };
      };
    };
  };
  deleteComment: {
    parameters: {
      path: {
        taskId: number;
        commentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  getProject: {
    parameters: {
      path: {
        projectKey: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"];
        };
      };
    };
  };
  updateProject: {
    parameters: {
      path: {
        projectKey: string;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          projectDTO: string;
          attachments?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"];
        };
      };
    };
  };
  deleteProject: {
    parameters: {
      path: {
        projectKey: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  updateTask: {
    parameters: {
      path: {
        projectKey: string;
        taskKey: string;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          taskDTO: string;
          attachments?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TaskDTO"];
        };
      };
    };
  };
  deleteTask: {
    parameters: {
      path: {
        projectKey: string;
        taskKey: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  register: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserRegistrationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  getComments: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      path: {
        taskId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedResponseCommentDTO"];
        };
      };
    };
  };
  addComment: {
    parameters: {
      query?: {
        parentCommentId?: number;
      };
      path: {
        taskId: number;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          content: string;
          attachments?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CommentDTO"];
        };
      };
    };
  };
  reactToComment: {
    parameters: {
      query: {
        type: "LIKE" | "DISLIKE";
      };
      path: {
        taskId: number;
        commentId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CommentDTO"];
        };
      };
    };
  };
  getProjects: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedResponseProjectDTO"];
        };
      };
    };
  };
  createProject: {
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          projectDTO: string;
          attachments?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["ProjectDTO"];
        };
      };
    };
  };
  createTask: {
    parameters: {
      path: {
        projectKey: string;
      };
    };
    requestBody?: {
      content: {
        "multipart/form-data": {
          /** Format: int32 */
          userId?: number;
          taskDTO: string;
          attachments?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TaskDTO"];
        };
      };
    };
  };
  simulate: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["OptimizationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["OptimizationResultDTO"];
        };
      };
    };
  };
  apply: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ApplyOptimizationRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["AppliedSchedule"];
        };
      };
    };
  };
  markAsRead: {
    requestBody: {
      content: {
        "application/json": number[];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  markAllRead: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UnreadCount"];
        };
      };
    };
  };
  refresh: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["MessageResponse"];
        };
      };
    };
  };
  logout: {
    responses: {
      /** @description OK */
      200: {
        content: never;
      };
    };
  };
  login: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  updateEmailPreferences: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["EmailPreferencesRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["CurrentUserDTO"];
        };
      };
    };
  };
  updateSchedule: {
    parameters: {
      path: {
        projectKey: string;
        taskKey: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TaskScheduleRequest"];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["TaskDTO"];
        };
      };
    };
  };
  serveFile: {
    parameters: {
      path: {
        fileName: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": string;
        };
      };
    };
  };
  lookupByEmail: {
    parameters: {
      query: {
        email: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UserDTO"];
        };
      };
    };
  };
  getActivities: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
      path: {
        taskId: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedResponseTaskActivityDTO"];
        };
      };
    };
  };
  search: {
    parameters: {
      query: {
        q: string;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["SearchResultDTO"];
        };
      };
    };
  };
  getNotifications: {
    parameters: {
      query?: {
        page?: number;
        size?: number;
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["PagedResponseNotificationDTO"];
        };
      };
    };
  };
  getUnreadCount: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "*/*": components["schemas"]["UnreadCount"];
        };
      };
    };
  };
  streamNotifications: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "text/event-stream": components["schemas"]["SseEmitter"];
        };
      };
    };
  };
}
