create table comment_attachments (comment_id integer not null, attachment_url varchar(255));
create table comment_reactions (comment_id integer not null, id serial not null, user_id integer not null, type varchar(255) not null check (type in ('LIKE','DISLIKE')), primary key (id), unique (comment_id, user_id));
create table comments (author_id integer not null, id serial not null, parent_comment_id integer, task_id integer not null, edited_at timestamp(6) with time zone, timestamp timestamp(6) with time zone not null, version bigint, content TEXT not null, primary key (id));
create table notifications (id serial not null, is_read boolean not null, user_id integer not null, timestamp timestamp(6) with time zone not null, link varchar(255), message TEXT not null, type varchar(255) not null check (type in ('PROJECT_INVITATION','PROJECT_UPDATED','MEMBER_REMOVED','TASK_ASSIGNED','TASK_UPDATED','TASK_COMMENT','TASK_DELETED','COMMENT_REPLY','COMMENT_REACTION')), primary key (id));
create table project_attachments (project_id integer not null, attachment_url varchar(255));
create table project_dependencies (dependency_id integer not null, project_id integer not null, constraint pk_project_dependencies primary key (project_id, dependency_id));
create table project_members (project_id integer not null, user_id integer not null, constraint pk_project_members primary key (project_id, user_id));
create table projects (id serial not null, next_task_number integer not null, owner_id integer not null, version bigint, description TEXT, project_key varchar(255) not null unique, summary varchar(255) not null, created timestamp(6) with time zone not null, updated timestamp(6) with time zone not null, primary key (id));
create table refresh_tokens (user_id integer not null, created_at timestamp(6) with time zone not null, expiry_date timestamp(6) with time zone not null, id bigserial not null, token_hash varchar(255) not null, family_id varchar(64) not null, family_started_at timestamp(6) with time zone not null, consumed_at timestamp(6) with time zone, primary key (id), constraint uk_refresh_token_hash unique (token_hash));
create table stored_files (id bigserial not null, stored_name varchar(255) not null, project_id integer, uploaded_by integer, created_at timestamp(6) with time zone not null, primary key (id), constraint uk_stored_file_name unique (stored_name));
create table task_activities (author_id integer not null, id serial not null, task_id integer not null, timestamp timestamp(6) with time zone not null, field_name varchar(255), new_value TEXT, old_value TEXT, type varchar(255) not null check (type in ('CREATED','STATUS_CHANGED','PRIORITY_CHANGED','ASSIGNEE_CHANGED','PROGRESS_CHANGED','DATES_CHANGED','SUMMARY_CHANGED','DESCRIPTION_CHANGED','LABELS_CHANGED','DEPENDENCIES_CHANGED','ATTACHMENTS_CHANGED','COMMENT_ADDED','COMMENT_EDITED','COMMENT_DELETED')), primary key (id));
create table task_attachments (task_id integer not null, attachment_url varchar(255));
create table task_dependencies (dependency_id integer not null, task_id integer not null, constraint pk_task_dependencies primary key (task_id, dependency_id));
create table tasks (assignee_id integer, due_date date, id serial not null, progress integer, project_id integer not null, start_date date, task_number integer not null, created timestamp(6) with time zone not null, updated timestamp(6) with time zone not null, version bigint, description TEXT, labels varchar(255), priority varchar(255) not null check (priority in ('LOWEST','LOW','MEDIUM','HIGH','HIGHEST')), status varchar(255) not null check (status in ('BACKLOG','GATHERING_INTEREST','TODO','WITHDRAWN','IN_PROGRESS','TO_REVIEW','TO_TEST','IN_TEST','READY_TO_MERGE','READY_TO_DEPLOY','RELEASED','DONE')), summary varchar(255) not null, primary key (id), constraint uk_task_project_number unique (project_id, task_number));
create table users (email_notifications_enabled boolean not null default true, email_on_comment_reply boolean not null default true, email_on_project_invitation boolean not null default true, email_on_task_assigned boolean not null default true, id serial not null, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, profile_picture varchar(255), version bigint not null, primary key (id));

create index idx_comment_task on comments (task_id);
create index idx_comment_author on comments (author_id);
create index idx_comment_parent on comments (parent_comment_id);
create index idx_comment_reaction_user on comment_reactions (user_id);
create index idx_notification_user_read on notifications (user_id, is_read);
create index idx_notification_user_timestamp on notifications (user_id, timestamp);
create index idx_project_owner on projects (owner_id);
create index idx_project_members_user on project_members (user_id);
create index idx_project_dep_dependency on project_dependencies (dependency_id);
create index idx_refresh_user on refresh_tokens (user_id);
create index idx_refresh_token_expiry on refresh_tokens (expiry_date);
create index idx_refresh_token_family on refresh_tokens (family_id);
create index idx_stored_file_project on stored_files (project_id);
create index idx_stored_file_uploader on stored_files (uploaded_by);
create index idx_task_activity_task on task_activities (task_id);
create index idx_task_activity_author on task_activities (author_id);
create index idx_task_activity_timestamp on task_activities (task_id, timestamp);
create index idx_task_attachments_t on task_attachments (task_id);
create index idx_task_dep_dependency on task_dependencies (dependency_id);
create index idx_task_project on tasks (project_id);
create index idx_task_assignee on tasks (assignee_id);
create index idx_comment_attachments_c on comment_attachments (comment_id);
create index idx_project_attachments_p on project_attachments (project_id);

-- Login looks users up by lower(email); this is the constraint that actually backs identity.
create unique index uk_users_email_lower on users (lower(email));

alter table if exists comment_attachments add constraint fk_comment_attachment_comment foreign key (comment_id) references comments on delete cascade;
alter table if exists comment_reactions add constraint fk_comment_reaction_comment foreign key (comment_id) references comments on delete cascade;
alter table if exists comment_reactions add constraint fk_comment_reaction_user foreign key (user_id) references users on delete cascade;
alter table if exists comments add constraint fk_comment_author foreign key (author_id) references users on delete cascade;
alter table if exists comments add constraint fk_comment_parent foreign key (parent_comment_id) references comments on delete cascade;
alter table if exists comments add constraint fk_comment_task foreign key (task_id) references tasks on delete cascade;
alter table if exists notifications add constraint fk_notification_user foreign key (user_id) references users on delete cascade;
alter table if exists project_attachments add constraint fk_project_attachment_project foreign key (project_id) references projects on delete cascade;
alter table if exists project_dependencies add constraint fk_project_dependency_dependency foreign key (dependency_id) references projects on delete cascade;
alter table if exists project_dependencies add constraint fk_project_dependency_project foreign key (project_id) references projects on delete cascade;
alter table if exists project_members add constraint fk_project_member_user foreign key (user_id) references users on delete cascade;
alter table if exists project_members add constraint fk_project_member_project foreign key (project_id) references projects on delete cascade;
alter table if exists projects add constraint fk_project_owner foreign key (owner_id) references users on delete restrict;
alter table if exists refresh_tokens add constraint fk_refresh_token_user foreign key (user_id) references users on delete cascade;
alter table if exists stored_files add constraint fk_stored_file_project foreign key (project_id) references projects on delete cascade;
alter table if exists stored_files add constraint fk_stored_file_uploader foreign key (uploaded_by) references users on delete set null;
alter table if exists task_activities add constraint fk_task_activity_author foreign key (author_id) references users on delete cascade;
alter table if exists task_activities add constraint fk_task_activity_task foreign key (task_id) references tasks on delete cascade;
alter table if exists task_attachments add constraint fk_task_attachment_task foreign key (task_id) references tasks on delete cascade;
alter table if exists task_dependencies add constraint fk_task_dependency_dependency foreign key (dependency_id) references tasks on delete cascade;
alter table if exists task_dependencies add constraint fk_task_dependency_task foreign key (task_id) references tasks on delete cascade;
alter table if exists tasks add constraint fk_task_assignee foreign key (assignee_id) references users on delete set null;
alter table if exists tasks add constraint fk_task_project foreign key (project_id) references projects on delete cascade;
