package com.backend.entities;

public enum TaskActivityType {
    CREATED,
    STATUS_CHANGED,
    PRIORITY_CHANGED,
    ASSIGNEE_CHANGED,
    PROGRESS_CHANGED,
    DATES_CHANGED,
    SUMMARY_CHANGED,
    DESCRIPTION_CHANGED,
    LABELS_CHANGED,
    DEPENDENCIES_CHANGED,
    ATTACHMENTS_CHANGED,
    COMMENT_ADDED,
    COMMENT_EDITED,
    COMMENT_DELETED
}
