export const TIMELINE_CONSTANTS = {
    DAY_WIDTH: 25,
    SIDEBAR_EXPANDED_WIDTH: 280,
    SIDEBAR_COLLAPSED_WIDTH: 48,
    TIMELINE_END_PADDING: 300,
};

export const getSidebarWidth = (isCollapsed: boolean) =>
    isCollapsed
        ? TIMELINE_CONSTANTS.SIDEBAR_COLLAPSED_WIDTH
        : TIMELINE_CONSTANTS.SIDEBAR_EXPANDED_WIDTH;
