export const TIMELINE_CONSTANTS = {
    DAY_WIDTH: 25,
    SIDEBAR_EXPANDED_WIDTH: 280,
    SIDEBAR_COLLAPSED_WIDTH: 48,
    TASK_ROW_HEIGHT_COLLAPSED: 36,
    TASK_ROW_HEIGHT_EXPANDED: 54,
    CROSS_PROJECT_DEPENDENCY_OFFSET: 1.4,
    TIMELINE_END_PADDING: 300,
};

export const getTaskRowHeight = (isSidebarCollapsed) =>
    isSidebarCollapsed
        ? TIMELINE_CONSTANTS.TASK_ROW_HEIGHT_COLLAPSED
        : TIMELINE_CONSTANTS.TASK_ROW_HEIGHT_EXPANDED;

export const getSidebarWidth = (isCollapsed) =>
    isCollapsed
        ? TIMELINE_CONSTANTS.SIDEBAR_COLLAPSED_WIDTH
        : TIMELINE_CONSTANTS.SIDEBAR_EXPANDED_WIDTH;

export default TIMELINE_CONSTANTS;
